# Generated by Django 5.2 on 2025-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.FileField(upload_to="reconciliation/source/")),
                ("target", models.FileField(upload_to="reconciliation/target/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("PROCESSED", "Processed"),
                            ("SCHEDULED", "Scheduled"),
                            ("INPROGRESS", "Inprogress"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
